### ISSUE TITLE
Symbol in system libraries that is not present on the iPhone

### ISSUE THREAD

**Issue by phamquochoan** [EFEducationFirstMobile/librabbitmq-objc#1]
Hi,

Currently I'm trying to implement this library into my IOS's project.
First of all, I just copied the `rabbitmq-c` and all the wrapper classes into my project. Build it. Successed message show up.

Then, I began to write some code:

```
AMQPConnection *connection = [[AMQPConnection alloc] init];
[connection connectToHost:@"123.45.678.90" onPort:12345];
[connection loginAsUser:@"test" withPassword:@"test" onVHost:@"/"];
AMQPChannel *channel = [connection openChannel]
```

However, I got this error after `[[AMQPConnection alloc] init];` 
##### Detected an attempt to call a symbol in system libraries that is not present on the iPhone: fcntl$UNIX2003 called from function amqp_open_socket_noblock in image MyApp.

Googling this error doesn't help much.
I need some help, thanks in advanced.

**Comment by dmakarenko** [comment]
Hi,

Thanks for opening an issue. The fix was pushed recently:  53e08299a19cfaaf5e02a7007cde30ca9102e4c0
